In [16]:
import torch
import numpy as np
from torch import nn,optim

#Linear Regression

In [13]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]], dtype=torch.float32)
y = torch.tensor([[1],[2],[3]])

In [71]:
class LR(nn.Module):
  def __init__(self,input_size, output_size) -> None:
      super().__init__()
      self.linear = nn.Linear(input_size,output_size)

  def forward(self,x):
    return self.linear(x)

In [15]:
model = LR(3,1)
model(x)

tensor([[1.8262],
        [4.2853],
        [6.7445]], grad_fn=<AddmmBackward0>)

In [17]:
from torch.utils.data import Dataset,DataLoader

In [98]:
class Data2D(Dataset):
  def __init__(self) -> None:
      super().__init__()
      self.x = torch.randint(0,10,(20,2),dtype=torch.float32)
      self.w = torch.randn((2,1))
      self.b = 3
      self.y = self.x @ self.w + self.b
      self.len = len(x)

  def __getitem__(self, index):
      return self.x[index],self.y[index]
  
  def __len__(self):
    return self.len


In [99]:
dataset = Data2D()
model = LR(2,1)

In [100]:
#not trained
criterion = nn.MSELoss()
criterion(model(dataset.x),dataset.y), list(model.parameters())

(tensor(38.5162, grad_fn=<MseLossBackward0>), [Parameter containing:
  tensor([[ 0.3563, -0.4303]], requires_grad=True), Parameter containing:
  tensor([-0.5776], requires_grad=True)])

In [101]:
#training
trainloader = DataLoader(dataset= dataset,batch_size = 2)
optimizer = optim.SGD(model.parameters(), lr = 0.001)

epochs = 100

for epoch in range(epochs):
  for x,y in trainloader:
    yhat = model(x)
    loss = criterion(yhat,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [102]:
criterion(model(dataset.x),dataset.y), list(model.parameters())

(tensor(3.1069, grad_fn=<MseLossBackward0>), [Parameter containing:
  tensor([[-0.6293, -0.7052]], requires_grad=True), Parameter containing:
  tensor([-0.5368], requires_grad=True)])

#Logistic Regression

In [141]:
class Data2D(Dataset):
  def __init__(self) -> None:
      super().__init__()
      self.x = torch.randn((50,2),dtype = torch.float32)
      self.y = torch.randint(0,2,(50,1),dtype = torch.float32)
      self.len = len(x)

  def __getitem__(self, index):
    return self.x[index], self.y[index]

  def __len__(self):
    return self.len     

In [142]:
class LogisticRegression(nn.Module):
  def __init__(self,input_size, output_size ):
    super().__init__()
    self.linear = nn.Linear(input_size,output_size)

  def forward(self,x):
    return torch.sigmoid(self.linear(x))

In [165]:
dataset = Data2D()
model = LogisticRegression(input_size = 2,output_size =1)

criterion = nn.BCELoss()
criterion(dataset.y, model(dataset.x)),list(model.parameters())

(tensor(53.7377, grad_fn=<BinaryCrossEntropyBackward0>), [Parameter containing:
  tensor([[ 0.2279, -0.5718]], requires_grad=True), Parameter containing:
  tensor([-0.4156], requires_grad=True)])

In [166]:
trainloader = DataLoader(dataset,batch_size = 1)
optimizer = optim.SGD(model.parameters(),lr = 0.1)
epochs = 1_000

for epoch in range(epochs):
  for x,y in trainloader:
    yhat = model(x)
    loss = criterion(yhat,y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

In [167]:
criterion(dataset.y, model(dataset.x)),list(model.parameters())

(tensor(53.9995, grad_fn=<BinaryCrossEntropyBackward0>), [Parameter containing:
  tensor([[ 1.3087, -0.9174]], requires_grad=True), Parameter containing:
  tensor([-6.6585], requires_grad=True)])